Adding Wavefront support
spring-cloud-incubator/spring-cloud-sleuth-otel pull request #12
Opened 2021-02-18 10:09 UTC by marcingrzejszczak

2021-02-18 23:58 UTC, jonatan-ivanov requested changes

2021-02-18 23:58 UTC, jonatan-ivanov commented on spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/wavefront/WavefrontOtelAutoConfiguration.java
> + * Auto-configuration} enables reporting to Wavefront.
```suggestion
 * {@link org.springframework.boot.autoconfigure.EnableAutoConfiguration}
 * Auto-configuration enables reporting to Wavefront.
```

2021-02-18 23:58 UTC, jonatan-ivanov commented on spring-cloud-sleuth-otel/src/main/java/org/springframework/cloud/sleuth/otel/bridge/OtelFinishedSpan.java
> +	volatile String linkLocalIp;
`private`?

2021-02-19 12:36 UTC, marcingrzejszczak commented
After talking to Stephane Nicoll I'm closing this PR in favour of https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/pull/16. The Wavefront-Sleuth integration will remain in Wavefront for the time being. You can read more about this here https://github.com/wavefrontHQ/wavefront-spring-boot/pull/104

2021-02-19 12:36 UTC, closed without merging