Allow injecting HttpServerAttributesExtractor and allow override of toURI method
spring-cloud-incubator/spring-cloud-sleuth-otel pull request #88
Opened 2021-11-08 19:38 UTC by bmistry13

This will allow me to inject My own implementation of SpringHttpServerAttributesExtractor toURI method will be overridden by following so illegal char will NOT cause parsing issue on OTL implementation.

2021-11-08 19:38 UTC, pivotal-cla commented
@bmistry13 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=88)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=88) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-11-08 19:38 UTC, pivotal-cla commented
@bmistry13 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=88)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=88) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-11-08 19:42 UTC, pivotal-cla commented
@bmistry13 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud-incubator/spring-cloud-sleuth-otel&pullRequestId=88)!

2021-11-09 07:53 UTC, marcingrzejszczak requested changes
I would remove 1 constructor but other than that LGTM. WDYT @iNikem ?

2021-11-09 07:53 UTC, marcingrzejszczak commented on spring-cloud-sleuth-otel/src/main/java/org/springframework/cloud/sleuth/otel/bridge/OtelHttpServerHandler.java
> +	public OtelHttpServerHandler(OpenTelemetry openTelemetry, HttpRequestParser httpServerRequestParser,
I don't think we need this constructor, we can safely remove it

2021-11-09 09:14 UTC, iNikem commented
Assuming use-case is real (how come your url contains illegal chars? shouldn't you instead fix that?) this way to solve it seems Ok. @marcingrzejszczak it is up to you, if you want to increase your public surface by making two more classes public.

2021-11-09 12:18 UTC, marcingrzejszczak commented
Yeah I must have missed that element. @bmistry13 how can your URL contain invalid chars? What's the business reasoning around this?

2021-11-09 17:49 UTC, bmistry13 commented
@marcingrzejszczak and @marcingrzejszczak,  It is a legacy system and we proxy our calls to the legacy system.  In fact, spring boot or tomcat allow via server.tomcat.relaxed-query-chars=[,],| to allow illegal char in URL. When we do this, the tomcat does not break.  In my opinion, the spring-sleuth library should work with or without illegal char.   I understand it is NOT 98% use case (it is corner case) but in rare cases, spring-sleuth should not fail to parse url.   Another option is to create a bean that be be injectable to parse URL.  Let me know what you think.

2021-11-10 11:15 UTC, closed without merging

2021-11-10 11:16 UTC, marcingrzejszczak commented
So @bmistry13 I've done this commit https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/commit/a05ae1e7fdc8d607f1f0ad14e32dddcc4b4b19b4 and with it you can inject your own implementation that can do whatever you want.

2021-11-11 03:49 UTC, bmistry13 commented
Thank you so much for your fast review and merging!